-- Migration: Create news table
-- Description: ニュースデータを格納するテーブル。日付をプライマリキーとして毎日1レコードを保存
-- Reference: https://supabase.com/docs/guides/database/tables

-- newsテーブル: ニュースの要約データを保存
-- 毎日8:00 JSTにバッチ処理でupsertされる
CREATE TABLE IF NOT EXISTS news (
  -- 日付（YYYY-MM-DD形式）をプライマリキーとして使用
  -- 同日に複数回バッチ実行しても冪等性を確保
  date DATE PRIMARY KEY,
  
  -- 世界ニュースのタイトルと要約（約2000文字）
  world_news_title TEXT NOT NULL,
  world_news_summary TEXT NOT NULL,
  
  -- 日本ニュースのタイトルと要約（約2000文字）
  japan_news_title TEXT NOT NULL,
  japan_news_summary TEXT NOT NULL,
  
  -- レコード作成日時（タイムゾーン付き）
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- レコード更新日時（upsert時に更新）
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 日付でのソート・検索を高速化するためのインデックス
-- 最新のニュースを取得するクエリで使用
CREATE INDEX IF NOT EXISTS idx_news_date ON news (date DESC);

-- コメント: テーブルの用途を記載
COMMENT ON TABLE news IS 'Daily news summaries generated by batch processing';
COMMENT ON COLUMN news.date IS 'Date of the news in YYYY-MM-DD format (primary key)';
COMMENT ON COLUMN news.world_news_title IS 'Title of world news summary';
COMMENT ON COLUMN news.world_news_summary IS 'AI-generated summary of world news (approx. 2000 chars)';
COMMENT ON COLUMN news.japan_news_title IS 'Title of Japan news summary';
COMMENT ON COLUMN news.japan_news_summary IS 'AI-generated summary of Japan news (approx. 2000 chars)';
