-- Migration: Create terms table
-- Description: 投資用語データを格納するテーブル。毎日3つの用語を保存
-- Reference: https://supabase.com/docs/guides/database/tables

-- termsテーブル: 投資用語データを保存
-- 毎日8:00 JSTにバッチ処理でinsertされる（1日3件）
CREATE TABLE IF NOT EXISTS terms (
  -- 自動採番のID
  id SERIAL PRIMARY KEY,
  
  -- 配信日（YYYY-MM-DD形式）
  -- 同日に複数の用語が紐づく（1日3件）
  date DATE NOT NULL,
  
  -- 用語名
  name TEXT NOT NULL,
  
  -- 用語の説明（約500文字）
  description TEXT NOT NULL,
  
  -- 難易度レベル（初心者・中級者・上級者）
  -- CHECK制約で許可される値を制限
  difficulty TEXT NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  
  -- レコード作成日時
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 日付でのソート・検索を高速化するためのインデックス
-- 今日の用語を取得するクエリで使用
CREATE INDEX IF NOT EXISTS idx_terms_date ON terms (date DESC);

-- コメント: テーブルの用途を記載
COMMENT ON TABLE terms IS 'Daily investment terms generated by batch processing (3 terms per day)';
COMMENT ON COLUMN terms.date IS 'Delivery date of the term in YYYY-MM-DD format';
COMMENT ON COLUMN terms.name IS 'Name of the investment term';
COMMENT ON COLUMN terms.description IS 'AI-generated description of the term (approx. 500 chars)';
COMMENT ON COLUMN terms.difficulty IS 'Difficulty level: beginner, intermediate, or advanced';
